f=open("if_else.py","r")
for i in f:
    print(i)
d=f.readline(5)
print(d)
#f=open("athi.txt","w")
#f.write("athiraa")
#f.close()
# a=open("athi.txt","w")
# a.write("hiiiii....helooo")
# a.close()
# a=open("athi.txt","a")
# a.write("    athiraa")
# a.close()
#f=open("finame.txt","x")
#f.close()