a=[]
print(type(a))
a=["onion","chilli","tomato","potato","cabagge","drumstick"]
print(a)
b=["apple","orange","watermelon","grapes","guava","pomogranete"]
print(b)
a.append(33)
print(a)
b.insert(1,"plums")
print(b)
print(a+b)
a.pop()
print(a)
a.pop(1)
print(a)
a.append(b)
print(a)
a.reverse()
print(a)
c=["c","d","b"]
c.sort(reverse=True)
print(c)